### ISSUE TITLE
Improvement Requset: Situation Aspects on the map

### ISSUE THREAD

**Issue by doct** [Sk1mble/modularFate#7]
Having the Fate Utility is great! I like that it allows to add Situation Aspects to a scene.
However, I do not understand where notes appear on the map. I'd like to be able to define where they appear, and move them around.
Also, currently, all notes put onto the map appear at the same place, overlapping each other which makes them all except one unreadable.
Currently, there is also no way to get rid of a note on the map except by deleting the aspect, which, well, deletes the aspect, which was probably not one wanted.

Thanks for you great module!

**Comment by Sk1mble** [comment]
Situation aspects are drawings that you manipulate on the drawing layer of Foundry, and can be moved, edited, or deleted from there. Please refer to the release notes for the system:

https://raw.githubusercontent.com/Sk1mble/modularFate/v1.7.4/release_notes

Under 1.3.5 it notes:

# Version 1.3.5
  Added a new feature in FateUtilities that lets you add a text note to the map for a situation aspect defined in the Aspects tab of FateUtilities.
  The first button creates a note (which is positioned at the centre of the visible portion of the screen)
  The second button pans to the note wherever it is, making it easier to find.
  The third button deletes the aspect and its related note as normal.
  The notes added with this function are drawings, so to move them or otherwise edit them you must use the Drawings layer.

**Comment by doct** [comment]
Sorry, I totally missed the "The notes added with this function are drawings, so to move them or otherwise edit them you must use the Drawings layer." part! Thanks! Awesome!
